language: php

#php:
#  - "7.4"

services:
  - docker

#before_cache:
#  # Save tagged docker images
#  - >
#    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
#    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
#
#before_install:
#  # Load cached docker images
#  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
#
#cache:
#  bundler: true
#  directories:
#    - $HOME/docker

#cache:
#  directories:
#    - $HOME/.composer/cache/files

cache: false

install:
#  - make build
  - make app-install
  - make app-init

script:
  - make app-code-check
  - make app-test
  - make app-test-coverage

after_success:
  - cd backend/
  - bash <(curl -s https://codecov.io/bash)
