version: '3'

services:
  web-server:
    image: nginx:1.15
    ports:
      - 8080:80
    volumes:
      - ./z_config/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/app/frontend/dist
      - ./backend/public/bundles:/app/backend/bundles
    depends_on:
      - frontend
      - backend
  backend:
    build:
      context: .
      dockerfile: z_config/backend/Dockerfile.fpm
    extra_hosts:
      WIN_HOST: ${WIN_HOST}
#    environment:
#      XDEBUG_CONFIG: "remote_host=172.27.80.1 remote_enable=1 remote_autostart=0 remote_port=9000"
#      PHP_IDE_CONFIG: "serverName=dev.blog.kz"
#      - XDEBUG_CONFIG=idekey=PHPSTORM remote_enable=1 remote_host=${WIN_HOST}
#      - PHP_IDE_CONFIG=serverName=dev.blog.kz
    volumes:
#      - /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./z_config/backend/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./backend:/app
    depends_on:
      - db
      - es
      - rabbit_mq
      - redis
      - centrifugo
  worker_indexer:
    build:
      context: .
      dockerfile: z_config/backend/Dockerfile.cli
    extra_hosts:
      WIN_HOST: ${WIN_HOST}
    volumes:
      - ./z_config/backend/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./backend:/app
    restart: always
    scale: 1
    command: bash -c "until $$(curl --output /dev/null --silent --head --fail http://rabbit_mq:15672); do echo 'Waiting RabbitMQ...'; sleep 1; done && php bin/console messenger:consume async_es -vv"
    depends_on:
      - db
      - es
      - rabbit_mq
      - redis
      - centrifugo
      - mailer
  worker_email:
    build:
      context: .
      dockerfile: z_config/backend/Dockerfile.cli
    extra_hosts:
      WIN_HOST: ${WIN_HOST}
    volumes:
      - ./z_config/backend/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./backend:/app
    restart: always
    scale: 2
    command: bash -c "until $$(curl --output /dev/null --silent --head --fail http://rabbit_mq:15672); do echo 'Waiting RabbitMQ...'; sleep 1; done && php bin/console messenger:consume async_email -vv"
    depends_on:
      - db
      - rabbit_mq
      - redis
      - centrifugo
      - mailer
  frontend:
    build:
      context: .
      dockerfile: z_config/frontend/Dockerfile
    command: ng serve --host frontend --public-host http://dev.blog.kz:8080 --disableHostCheck true
    tty: true
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - centrifugo
  db:
    image: mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ''
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  rabbit_mq:
    image: rabbitmq:3.8.9-management
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:15672"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
  centrifugo:
    image: centrifugo/centrifugo:v2.8
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      CENTRIFUGO_SECRET: secret
      CENTRIFUGO_API_KEY: secret
    volumes:
      - ./z_config/centrifugo:/centrifugo
    ports:
      - "8083:8000"
    command: centrifugo --admin --admin_insecure
volumes:
  db_data:
    driver: local
  es_data:
    driver: local
