version: '3.9'

services:
  web-server:
    container_name: blog_web_server
    image: researcher2286/blog_nginx:${TAG}
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - backend
      - centrifugo
    networks:
      - blog
  backend:
    container_name: blog_backend
    image: researcher2286/blog_backend:${TAG}
    restart: unless-stopped
    depends_on:
      - db
      - es
      - rabbit-mq
      - redis
      - centrifugo
    networks:
      - blog
  worker-indexer:
    container_name: blog_worker_indexer
    image: researcher2286/blog_worker:${TAG}
    restart: unless-stopped
    command: bash -c "
      wait-for-it db:5432 -s -t 60 &&
      wait-for-it redis:6379 -s -t 60 &&
      wait-for-it rabbit-mq:5672 -s -t 60 &&
      wait-for-it es:9200 -s -t 60 &&
      wait-for-it centrifugo:8000 -s -t 60 &&
      php bin/console messenger:consume async_es -vv"
    depends_on:
      - db
      - es
      - rabbit-mq
      - redis
      - centrifugo
    networks:
      - blog
  worker-plagiarism:
    container_name: blog_worker_plagiarism
    image: researcher2286/blog_worker:${TAG}
    restart: unless-stopped
    command: bash -c "
      wait-for-it db:5432 -s -t 60 &&
      wait-for-it redis:6379 -s -t 60 &&
      wait-for-it rabbit-mq:5672 -s -t 60 &&
      wait-for-it es:9200 -s -t 60 &&
      wait-for-it centrifugo:8000 -s -t 60 &&
      php bin/console messenger:consume async_plagiarism -vv"
    depends_on:
      - db
      - es
      - rabbit-mq
      - redis
      - centrifugo
    networks:
      - blog
  worker-email:
    container_name: blog_worker_email
    image: researcher2286/blog_worker:${TAG}
    restart: unless-stopped
    command: bash -c "
      wait-for-it db:5432 -s -t 60 &&
      wait-for-it redis:6379 -s -t 60 &&
      wait-for-it rabbit-mq:5672 -s -t 60 &&
      wait-for-it centrifugo:8000 -s -t 60 &&
      php bin/console messenger:consume async_email -vv"
    depends_on:
      - db
      - rabbit-mq
      - redis
      - centrifugo
    networks:
      - blog
  worker-telegram:
    container_name: blog_worker_telegram
    image: researcher2286/blog_worker:${TAG}
    restart: unless-stopped
    command: bash -c "
      wait-for-it db:5432 -s -t 60 &&
      wait-for-it redis:6379 -s -t 60 &&
      wait-for-it rabbit-mq:5672 -s -t 60 &&
      wait-for-it centrifugo:8000 -s -t 60 &&
      php bin/console messenger:consume async_telegram -vv"
    depends_on:
      - db
      - rabbit-mq
      - redis
      - centrifugo
    networks:
      - blog
  db:
    container_name: blog_db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    networks:
      - blog
  redis:
    container_name: blog_redis
    image: redis:6.0
    restart: unless-stopped
    networks:
      - blog
  es:
    container_name: blog_es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - blog
  rabbit-mq:
    container_name: blog_rabbit_mq
    image: rabbitmq:3.8.9-management
    restart: unless-stopped
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - blog
  centrifugo:
    container_name: blog_centrifugo
    image: researcher2286/blog_centrifugo:${TAG}
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      CENTRIFUGO_SECRET: secret
      CENTRIFUGO_API_KEY: secret
    ports:
      - "8083:8000"
    command: centrifugo
    networks:
      - blog

volumes:
  db_data:
    name: blog_db_data
    driver: local
  es_data:
    name: blog_es_data
    driver: local

networks:
  blog:
    name: blog
    driver: bridge
