framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async_es:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 1
                options:
                    # queue_name is specific to the doctrine transport
#                    queue_name: es

                    # for AMQP send to a separate exchange then queue
                    exchange:
                        name: es
                    queues:
                        messages_es: ~
#                    queue:
#                        name: 'pubsub_%rand(5)%'
#                        binding_keys: pubsub
#                        exchange:
#                            name: pubsub
#                            type: fanout
                    # or redis try "group"
            async_plagiarism:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 1
                options:
                    exchange:
                        name: plagiarism
                    queues:
                        messages_plagiarism: ~
            async_email:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 1 # Дублирует сообщение воркерам, если поставить 2 то сообщение придет на обработку двум воркерам
                options:
                    exchange:
                        name: email
                    queues:
                        messages_email: ~
            async_telegram:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 1
                options:
                    exchange:
                        name: telegram
                    queues:
                        messages_email: ~

            # https://symfony.com/doc/current/messenger.html#transport-configuration
#             async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            App\Message\Article\IndexingArticleMessage: async_es
            App\Message\Article\PlagiarismArticleMessage: async_plagiarism
            App\Message\Article\SendEmailMessage: async_email
            App\Message\Article\SendTelegramMessage: async_telegram
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
