nelmio_api_doc:
  models: { use_jms: false }
  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc$)(?!/_.)
#    host_patterns:
#      - ^/api/users
  documentation:
    info:
      title: Blog
      description: Blog API
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
